../../../pyodbc.pyi,sha256=lVTrjquwnlBRKvppPS-CifIDyFRZDkx03RGjDZo_rXo,13102
pyodbc-4.0.32.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
pyodbc-4.0.32.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.32.dist-info/METADATA,sha256=UXVCMR-bEEIK2HPIj62wiTsogopWW_yjL_mJzzUXamU,2283
pyodbc-4.0.32.dist-info/RECORD,,
pyodbc-4.0.32.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
pyodbc-4.0.32.dist-info/WHEEL,sha256=nTy_Z8ivGEB6qFwVLg7_h6rq0Jt0JU5Pz2cL2_FjSMQ,105
pyodbc-4.0.32.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc.cpython-310-x86_64-linux-gnu.so,sha256=7FJE3Mg-PL_x_SPAtqspOl8lxs1ERXFp-2u8D_cW8qs,708120
